name: Dispatch

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  payload:
    name: Dispatch
    runs-on: ubuntu-latest

    steps:
      - name: Create Payload
        run: |
          cat > payload.json <<EOF
          {
            "event": "${{ github.event_name == 'push' && 'push' || 'pr' }}",
            "actor": "${{ github.event.pull_request.user.login || github.actor }}",
            "pr_number": "${{ github.event.pull_request.number }}",
            "head_ref": "${{ github.event.pull_request.head.ref || github.ref }}",
            "base_ref": "${{ github.event.pull_request.base.ref || github.ref_name }}"
          }
          EOF

      - name: Upload Payload
        uses: actions/upload-artifact@v6
        with:
          name: payload
          path: payload.json
